from __future__ import annotations

from pathlib import Path

from PIL import Image

from app.core.db import session_scope
from app.core.models import Production
from app.editing.ffmpeg import run_ffmpeg
from app.editing.synth import synth_segment
from app.llm.mock import MockLLM
from app.manual_video.workflow import inbox_for
from app.pipeline.orchestrator import Orchestrator


def _fill_inbox(orchestrator: Orchestrator, pid: str, settings) -> None:
    inbox = inbox_for(pid, orchestrator.storage, settings)
    for i in range(1, 6):
        synth_segment(inbox / f"segment_{i}.mp4", 1, "black", str(i), with_audio=True)


def _short_settings(settings):
    settings.veo.duration_seconds = 1
    settings.video.max_duration_s = 5
    settings.video.music_enabled = False
    settings.video.logo_watermark = False
    return settings


def test_new_production_persists(settings):
    o = Orchestrator(settings)
    pid = o.new_production()
    assert o.status(pid)["state"] == "DISCOVERING"


def test_manual_mock_pipeline_collects_and_renders(settings):
    settings = _short_settings(settings)
    o = Orchestrator(settings)
    pid = o.new_production()
    o.prepare(pid)
    _fill_inbox(o, pid, settings)
    o.collect(pid)
    final = o.finish(pid)
    assert final.exists() and o.status(pid)["state"] == "READY"


def test_prepare_is_idempotent_and_does_not_regenerate(settings):
    settings = _short_settings(settings)
    llm = MockLLM()
    o = Orchestrator(settings, llm=llm)
    pid = o.new_production()
    first = o.prepare(pid)
    calls_after_first = len(llm.calls)
    assert calls_after_first > 0
    second = o.prepare(pid)
    assert len(llm.calls) == calls_after_first
    assert [p.name for p in first.prompt_files] == [p.name for p in second.prompt_files]
    with session_scope(o.engine) as s:
        p = s.get(Production, pid)
        assert p.script is not None and p.storyboard is not None and p.bible is not None
        assert len(p.prompts) == 5


def test_finish_persists_generated_metadata_not_placeholders(settings):
    settings = _short_settings(settings)
    o = Orchestrator(settings)
    pid = o.new_production()
    o.prepare(pid)
    _fill_inbox(o, pid, settings)
    o.collect(pid)
    o.finish(pid)
    with session_scope(o.engine) as s:
        p = s.get(Production, pid)
        meta = p.video_metadata
        assert meta is not None
        assert meta.description != "Original short generated by OneMoreShort."
        assert "#Shorts" in meta.hashtags
        assert meta.title and len(meta.title) <= 100
        assert p.final_video is not None and p.final_video.passed is True
        assert p.caption is not None and Path(p.caption.ass_path).exists()
        kinds = {asset.kind for asset in p.audio_assets}
        assert "narration_beat" in kinds and "mix" in kinds


def test_publish_collect_and_learn_loop_in_mock(settings):
    from datetime import UTC, datetime, timedelta

    settings = _short_settings(settings)
    settings.upload.enabled = True
    settings.intelligence.min_samples = 1
    t0 = datetime(2026, 9, 7, 12, 0, tzinfo=UTC)
    current = {"now": t0}
    o = Orchestrator(settings, clock=lambda: current["now"])
    pid = o.new_production()
    o.prepare(pid)
    _fill_inbox(o, pid, settings)
    o.collect(pid)
    o.finish(pid)
    assert o.status(pid)["state"] == "PUBLISHED"
    assert o.status(pid)["youtube_video_id"].startswith("mock-")

    current["now"] = t0 + timedelta(hours=1)
    assert o.collect_analytics() == [pid]
    assert o.status(pid)["state"] == "ANALYZING" and o.status(pid)["snapshots"] == 1

    current["now"] = t0 + timedelta(days=8)
    o.collect_analytics()
    summary = o.learn()
    assert summary.videos == 1 and "What hooks work?" in summary.answers
    report = o.report(pid)
    assert "VIDEO PERFORMANCE REPORT" in report and "NEXT VIDEO RECOMMENDATION" in report
    assert o.status(pid)["state"] == "LEARNED"

    metrics = o.metrics()
    assert metrics["videos_generated"] == 1 and metrics["videos_published"] == 1
    assert metrics["generation_success_rate"] == 1.0 and metrics["failure_rate"] == 0.0


def test_daily_creates_and_prepares_one_production_then_waits_for_clips(settings):
    settings = _short_settings(settings)
    o = Orchestrator(settings)
    summary = o.daily()
    assert summary["production_id"].startswith("OMS-")
    assert summary["state"] == "GENERATING" and summary["waiting_for_clips"] is True
    again = o.daily()
    assert again["production_id"] == summary["production_id"], "daily never starts a second production the same day"


def test_resume_raises_precise_human_action_while_clips_are_missing(settings):
    from app.core.errors import HumanActionRequired

    settings = _short_settings(settings)
    o = Orchestrator(settings)
    pid = o.new_production()
    try:
        o.resume(pid)
    except HumanActionRequired as err:
        assert "0/5" in err.problem and pid in err.next_step
    else:
        raise AssertionError("resume must stop for the operator when the inbox is empty")
    _fill_inbox(o, pid, settings)
    assert o.resume(pid) == "READY"


def test_finish_uses_music_and_logo_when_configured(settings, tmp_path):
    settings = _short_settings(settings)
    assets = tmp_path / "assets"
    (assets / "music").mkdir(parents=True)
    run_ffmpeg(["-y", "-f", "lavfi", "-i", "sine=frequency=110:sample_rate=48000:duration=3", "-c:a", "pcm_s16le",
                str(assets / "music" / "bed.wav")], cwd=assets)
    Image.new("RGBA", (300, 120), (255, 0, 0, 255)).save(assets / "logo.png")
    settings.paths.assets_dir = str(assets)
    settings.video.music_enabled = True
    settings.video.logo_watermark = True
    settings.video.logo_path = str(assets / "logo.png")
    o = Orchestrator(settings)
    pid = o.new_production()
    o.prepare(pid)
    _fill_inbox(o, pid, settings)
    o.collect(pid)
    final = o.finish(pid)
    assert final.exists()
    with session_scope(o.engine) as s:
        p = s.get(Production, pid)
        assert any(asset.kind == "music" for asset in p.audio_assets)
